### ISSUE TITLE
Compile error with gcc 4.8.2

### ISSUE THREAD

**Issue by patburke** [munificent/wren#142]
Using gcc 4.8.2 on Ubuntu 14.04.

```
src/wren_vm.c: In function ‘runInterpreter’:
src/wren_vm.c:384:41: error: operation on ‘fiber->stackTop’ may be undefined [-Werror=sequence-point]
   #define PUSH(value)  (*fiber->stackTop++ = value)
                                         ^
src/wren_vm.c:562:23: note: in expansion of macro ‘PUSH’
     CASE_CODE(DUP):   PUSH(PEEK()); DISPATCH();
                       ^
```

**Comment by MarcoLizza** [comment]
Did notice it too, in the Travis CI output. Quite odd.

**Comment by patburke** [comment]
It appears to be caused by e740a4c95 adding [line 563 to wren_vm.c](https://github.com/munificent/wren/blob/e740a4c95a67f7e967aceb7bfb8f7a2197d899eb/src/wren_vm.c#L563).

**Comment by zeckalpha** [comment]
Here's those two macros expanded:

~~~ C
(*fiber->stackTop++ = (*(fiber->stackTop - 1)))
~~~

Might it be undefined due to the `++`? Perhaps these should be multi-line macros to make the intent clearer / more defined.

**Comment by munificent** [comment]
Yeah, my mistake. It's fixed now. :)

For some reason, clang doesn't complain about it, so I didn't catch this locally.

**Comment by munificent** [comment]
@zeckalpha I think it might be the `=`? Either way, the result of the expansion is an expression where there isn't a defined sequence point between accessing and setting `stackTop`.

**Comment by MarcoLizza** [comment]
Neither MSC with the default settings complains about it. Nor Cppcheck.

It is due to the post increment operator, @zeckalpha is right.

The evaluation order of the subexpressions is not defined (and mostly compiler dependant), and the post increment side effect could affect the outcome.

(l-value subexpressions are not necessarily evaluated after the r-value ones)
